//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud_application_web_api.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public int T_id { get; set; }
        public string T_name { get; set; }
        public string T_priority { get; set; }
        public System.DateTime Date { get; set; }
    }
}
